name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: get-project
        name: Get project name
        run: |
          PROJECT_URL=$(cat project-to-build)
          echo "::set-output name=PROJECT::${PROJECT_URL}"
      - name: Clone project
        run: git clone --depth=1 $PROJECT project
        env:
          PROJECT: ${{ steps.get-project.outputs.PROJECT }}
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then ./gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
