name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate Gradle Wrapper
        run: |
          # Check if gradlew exists, and if not, generate it
          if [ ! -f "gradlew" ]; then
            ./gradle wrapper
          fi
          
          # Ensure gradlew has execute permissions
          chmod +x gradlew
      - id: get-project
        name: Get project name
        run: |
          PROJECT_URL=$(cat project-to-build)
          echo "PROJECT_URL=${PROJECT_URL}" >> $GITHUB_ENV
      - name: Clone project
        run: git clone --depth=1 $PROJECT_URL project
        env:
          PROJECT_URL: ${{ env.PROJECT_URL }}
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then ./gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
